name: Test Actions

on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        description: test version
        required: true

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Get Next Version
        id: next_version
        uses: madhead/semver-utils@latest
        with:
          version: ${{ github.event.inputs.version }}
      - name: Next Version
        run: |
          echo ${{ steps.next_version.outputs.inc-patch }}
          echo ${{ steps.next_version.outputs.inc-minor }}
          echo ${{ steps.next_version.outputs.inc-major }}
