name: Test Actions

on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        description: test version
        required: true

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Get Next Version
        id: next_version
        uses: technicallyjosh/next-version-action@v1
        with:
          version: ${{ github.event.inputs.version }}
          type: minor
      - name: Next Version
        run: |
          echo ${{ steps.next_version.outputs.next_version }}
          echo ${{ steps.next_version.outputs.next_version_number }}
